### ISSUE TITLE
SQL dump needed

### ISSUE THREAD

**Issue by atxcowboy** [alxspiker/AI-X#1]
Please provide a SQL dump to get started with the DB.

Later on it may be nice for users to have an installer.

**Comment by alxspiker** [comment]
Putting a dump now.

**Comment by alxspiker** [comment]
> Please provide a SQL dump to get started with the DB.
> 
> Later on it may be nice for users to have an installer.

And yes, definitely going to work on a multi-platform installer. Started this project a couple days ago and I plan to have it so anyone can use it by the end of this week. Ill have the chat working perfectly by end of day today, then I will start on document ingestion, api access, and more.
