### ISSUE TITLE
Is Demo Server Up and Running?

### ISSUE THREAD

**Issue by neeewwww** [alxspiker/AI-X#3]

**Comment by alxspiker** [comment]
I need to update it to the latest version with the working chat, was just working on the readme quickly.

**Comment by alxspiker** [comment]
Ill work on it right now and get it linked to the AI.

**Comment by alxspiker** [comment]
Getting an error with the chat function, give me a few more mins.

**Comment by alxspiker** [comment]
Fixed chat, 
![image](https://github.com/alxspiker/AI-X/assets/7357054/3107cfa4-cd6a-452f-9867-86b15463469c)

**Comment by alxspiker** [comment]
Connecting the python server right now.

**Comment by alxspiker** [comment]
Working 
![image](https://github.com/alxspiker/AI-X/assets/7357054/ec8caa6a-5722-47ab-b161-a86f89aa06bd)

**Comment by neeewwww** [comment]
I believe someone on casalioy repo's mentioned the idea of hosting it for the purpose of testing

**Comment by alxspiker** [comment]
Just fixed the registration. Going to add a default test@test.com login.

**Comment by neeewwww** [comment]
DNS_PROBE_FINISHED_NXDOMAIN on my side.

**Comment by alxspiker** [comment]
Yeah, it was down. Its up now. Seems like when I push an update it goes down for a little bit.

**Comment by neeewwww** [comment]
I'm still experiencing issues on my end. Do you have an IP address to access it? It's possible that the DNS hasn't updated yet.

**Comment by alxspiker** [comment]
Updating demo link now.

**Comment by neeewwww** [comment]
ERR_NGROK_3200
Tunnel ad05-199-126-87-169.ngrok-free.app not found

Gonna try to spin up on my machine and report back.
